apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
  namespace: pi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: mehditoumi/pi-eureka:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          readinessProbe:
            tcpSocket:
              port: 8761
            initialDelaySeconds: 20
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  namespace: pi
spec:
  selector:
    app: eureka
  ports:
    - port: 8761
      targetPort: 8761
