apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: pi
type: Opaque
stringData:
  username: root
  password: root
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb
  namespace: pi
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS prolance_users;
    CREATE DATABASE IF NOT EXISTS payement_db;
    CREATE DATABASE IF NOT EXISTS milestone_db;
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: pi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-proot"]
            initialDelaySeconds: 20
            periodSeconds: 5
      volumes:
        - name: mysql-data
          emptyDir: {}
        - name: mysql-initdb
          configMap:
            name: mysql-initdb
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: pi
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
