# ?? Server ????????????????????????????????????????????????????????????????????
server.port=8084

# ?? Application name ??????????????????????????????????????????????????????????
spring.application.name=microservice-user

# ?? DataSource ????????????????????????????????????????????????????????????????
spring.datasource.url=jdbc:mysql://localhost:3306/prolance_users?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&sessionVariables=default_storage_engine=InnoDB
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ?? JPA / Hibernate ???????????????????????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ?? Eureka Client ?????????????????????????????????????????????????????????????
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

# ?? Actuator ??????????????????????????????????????????????????????????????????
management.endpoints.web.exposure.include=health,info,metrics

# ?? Error Handling ????????????????????????????????????????????????????????????
spring.web.error.include-message=always
spring.web.error.include-binding-errors=always

# ?? JWT ???????????????????????????????????????????????????????????????????????
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# ?? Email verification token expiry (24h in ms) ???????????????????????????????
app.verification.token-expiry=86400000

# Mailtrap Sandbox
# spring.mail.host=sandbox.smtp.mailtrap.io
# spring.mail.port=2525
# spring.mail.username=eb367555f7faf4
# spring.mail.password=1a9dd4c484953f

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=midimidimidi98@gmail.com
spring.mail.password=cphrlnndqsbthckw

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# App mail config
app.mail.from=midimidimidi98@gmail.com
