eureka.client.service-url.defaultZone=${EUREKA_DEFAULT_ZONE:http://eureka:8761/eureka}
eureka.instance.prefer-ip-address=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://milestone-db:3306/milestone_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
